AGE_BINS = [0, 5, 12, 17, 24, 34, 44, 54, 64, 74, 999]
AGE_LABELS = [
    "0-5",
    "6-12",
    "13-17",
    "18-24",
    "25-34",
    "35-44",
    "45-54",
    "55-64",
    "65-74",
    "75 o más",
]

AMM_ID = [6, 9, 21, 18, 26, 31, 39, 46, 19, 48, 49]
PERIFERIA_ID = [10, 12, 25, 41, 45]

ID_TO_CITY_NAME = {
    39: "Monterrey",
    26: "Guadalupe",
    46: "San Nicolás de los Garza",
    6: "Apodaca",
    21: "Escobedo",
    19: "San Pedro Garza García",
    49: "Santiago",
    31: "Juárez",
    18: "García",
    48: "Santa Catarina",
    9: "Cadereyta",
    41: "Pesquería",
    10: "El Carmen",
    12: "Ciénega de Flores",
    25: "Zuazua",
    45: "Salinas Victoria",
    1: "Abasolo",
    2: "Agualeguas",
    4: "Allende",
    5: "Anáhuac",
    7: "Aramberri",
    8: "Bustamante",
    11: "Cerralvo",
    13: "China",
    14: "Doctor Arroyo",
    15: "Doctor Coss",
    16: "Doctor González",
    17: "Galeana",
    20: "General Bravo",
    22: "General Terán",
    23: "General Treviño",
    24: "General Zaragoza",
    47: "Hidalgo",
    28: "Higueras",
    29: "Hualahuises",
    30: "Iturbide",
    31: "Juárez",
    32: "Lampazos de Naranjo",
    33: "Linares",
    3: "Los Aldamas",
    27: "Los Herreras",
    42: "Los Ramones",
    34: "Marín",
    35: "Melchor Ocampo",
    36: "Mier y Noriega",
    37: "Mina",
    38: "Montemorelos",
    40: "Parás",
    43: "Rayones",
    44: "Sabinas Hidalgo",
    50: "Vallecillo",
    51: "Villaldama",
    100: "Fuera de Nuevo León",
    111: "Fuera del País",
    8888: "No sabe",
    9999: "No contesta",
}


ATTRIBUTE_LABELS = {
    "afiliacion_servicio_salud": "Afiliación a servicio de salud",
    "edad_anos": "Edad",
    "ingreso": "Ingreso",
    "modo_transporte": "Modo de transporte",
    "nivel_actual_estudios": "Nivel de estudios actual",
    "nivel_max_estudios": "Nivel máximo de estudios",
    "servicio_salud_donde_se_atendio": "Servicio de salud donde se atendió",
    "sexo": "Sexo",
    "tipo_consulta": "Tipo de consulta",
    "tipo_escuela": "Tipo de escuela",
    "tipo_trabajo": "Tipo de trabajo",
}

DESIRED_ORDERS = {
    "sexo": [
        "Hombre",
        "Mujer",
    ],
    "estudios": [
        "Ninguno",
        "Preescolar",
        "Primaria",
        "Secundaria",
        "Preparatoria o bachillerato general",
        "Bachillerato tecnológico",
        "Estudios técnicos o comerciales con primaria terminada",
        "Estudios técnicos o comerciales con secundaria terminada",
        "Estudios técnicos o comerciales con preparatoria terminada",
        "Normal con primaria o secundaria terminada",
        "Normal de licenciatura",
        "Licenciatura",
        "Especialidad",
        "Maestría",
        "Doctorado",
    ],
    "ingreso": [
        "Sin ingreso",
        "No contesta",
        "Menos de 1 SM ($1 - $8,364)",
        "1-2 SM ($8,364 - $16,728)",
        "2-3 SM ($16,728 - $25,092)",
        "3-4 SM ($25,092 - $33,456)",
        "4-5 SM ($33,456 - $41,820)",
        "5-6 SM ($41,820 - $50,184)",
        "6-7 SM ($50,184 - $58,548)",
        "7-8 SM ($58,548 - $66,912)",
        "8-9 SM ($66,912 - $75,276)",
        "9-10 SM ($75,276 - $83,640)",
        "10 o más SM ($83,640 o más)",
    ],
    "edad": [
        "0-5",
        "6-12",
        "13-17",
        "18-24",
        "25-34",
        "35-44",
        "45-54",
        "55-64",
        "65-74",
        "75 o más",
    ],
    "municipio": [
        "Apodaca",
        "Cadereyta",
        "Escobedo",
        "García",
        "Guadalupe",
        "Juárez",
        "Monterrey",
        "San Nicolás de los Garza",
        "San Pedro Garza García",
        "Santa Catarina",
        "Santiago",
        "AMM",
        "Periferia",
        "Resto NL",
        "Nuevo León",
    ],
    "tipo_escuela": ["Pública", "Privada", "Otro tipo"],
    "tipo_trabajo": ["Trabajo remunerado", "Trabajo no remunerado", "Otro"],
}

RECODES: dict = {
    "tipo_trabajo_remunerado": {
        "source_attribute": "tipo_trabajo",
        "label": "Tipo de trabajo (remunerado)",
        "buckets": [
            ("Trabajo remunerado", [1, 4, 6]),
            ("Trabajo no remunerado", [5]),
            ("Otro", None),
        ],
        "order": ["Trabajo remunerado", "Trabajo no remunerado", "Otro"],
    },
    "tipo_servicio_salud_publico_privado": {
        "source_attribute": "servicio_salud_donde_se_atendio",
        "label": "Tipo de servicio de salud (público/privado)",
        "buckets": [
            ("Públicos", [1, 4, 5, 6, 11]),
            ("Privados", [2, 3, 7, 8, 9, 10, 12, 13]),
        ],
        "order": ["Públicos", "Privados"],
    },
    "particion_modal_agregada": {
        "source_attribute": "modo_transporte",
        "label": "Partición modal agregada",
        "buckets": [
            ("Medios motorizados no colectivos", [3, 4, 5, 9]),
            ("Medios no motorizados", [1, 6, 7]),
            ("Transporte público colectivo", [2, 8, 10]),
            ("Transporte privado colectivo", [11, 12, 13]),
            ("Otros", [14, 15]),
            ("No sabe", [8888]),
            ("No contesta", [9999]),
        ],
        "order": [
            "Medios no motorizados",
            "Transporte público colectivo",
            "Transporte privado colectivo",
            "Medios motorizados no colectivos",
            "Otros",
            "No sabe",
            "No contesta",
        ],
    },
}


PRESETS: list = [
    {
        "key": "respuesta_por_unidad_geografica",
        "label": "Respuesta por unidad geográfica",
        "group_by": "city_id",
        "filters": [],
    },
    {
        "key": "respuesta_hombres_por_unidad_geografica",
        "label": "Respuesta de HOMBRES por unidad geográfica",
        "group_by": "city_id",
        "filters": [{"attribute": "sexo", "value": 0}],
    },
    {
        "key": "respuesta_mujeres_por_unidad_geografica",
        "label": "Respuesta de MUJERES por unidad geográfica",
        "group_by": "city_id",
        "filters": [{"attribute": "sexo", "value": 1}],
    },
    {
        "key": "respuesta_por_sexo",
        "label": "Respuesta por sexo",
        "group_by": "sexo",
        "filters": [],
    },
    {
        "key": "respuesta_por_edad",
        "label": "Respuesta por edad",
        "group_by": "edad_anos",
        "filters": [],
    },
    {
        "key": "respuesta_por_ano",
        "label": "Respuesta por año",
        "group_by": "year",
        "filters": [],
        # Sólo aplica a preguntas con `concept_id`; la UI lo oculta cuando la
        # pregunta seleccionada no tiene equivalencia entre olas.
        "requires_concept": True,
    },
]


DERIVED_NEXT: list[tuple[str, str]] = [
    ("tiempo_trabajo", "p3_1"),
    ("prestaciones", "p5_1"),
    ("trabajo_formal", "p5_1"),
    ("quehaceres_hogar", "p7_1"),
    ("cuidados_personas", "p8_1"),
    ("total_min_trabajo_rem_y_norem", "p1"),
    ("ocio", "p9_1"),
    ("tiempo_espera_consulta", "p103_1"),
    ("al_menos_un_problema_mental", "p107_1"),
    ("tiempo_espera", "p21_1"),
    ("costo_total_viaje_redondo", "p24"),
    ("tiempo_ida", "p27_1"),
    ("tiempo_regreso", "p28_1"),
    ("tiempo_total_traslado", "tiempo_ida"),
    ("usa_transporte_publico", "p17"),
    ("usa_metro", "p17"),
    ("victima_tp", "p39_1"),
    ("tiempo_camina", "p20_1"),
    ("num_discriminaciones", "p89_1"),
    ("al_menos_una_discriminacion", "p89_1"),
    ("num_acciones_pc", "p161_1"),
    ("al_menos_una_accion_pc", "p161_1"),
    ("p56_ultimos_5_anios", "p55"),
    ("p57_ultimos_5_anios", "p55"),
    ("p58_ultimos_5_anios", "p55"),
    ("p56_ultimos_10_anios", "p55"),
    ("p57_ultimos_10_anios", "p55"),
    ("p58_ultimos_10_anios", "p55"),
    ("al_menos_un_problema_agua", "p66"),
]
